### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by mystijk** [afruehstueck/VIVE3D#1]
after running it reported that :
No such file or directory {config.HOME}/projects/STIT/pretrained_models/79999_iter.pth 

Seems this path is defined in segmenter.py,so how to get it?

**Comment by afruehstueck** [comment]
You're correct, there was a missing explanation about the pre-trained segmentation model. I have amended the explanation in the Readme. Please find the instructions below:

We rely on an [implementation of BiSeNet](https://github.com/zllrunning/face-parsing.PyTorch) to obtain a segmentation of the face. Please download their [pretrained model](https://drive.google.com/file/d/154JgKpzCPW82qINcVieuPH3fZ2e0P812) to the folder `pretrained_models` in the project directory.
